name: Solidity Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          solc-version: 0.8.18
          node-version: 16
          sarif: results.sarif
          fail-on: none
          target: 'contracts/'
          slither-config: slither.config.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.18
          node-version: 16
          sarif: results.sarif
          fail-on: none
          target: 'contracts/'
          crytic-args: --solc-remaps '@=node_modules/@'
